/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Palavra;
import model.dao.PalavraDAO;
import model.dao.UsuarioDAO;

/**
 *
 * @author pivis
 */
public class Fase3 extends javax.swing.JFrame {

    /**
     * Creates new form Fase3
     */
    public Fase3() {
        super("Fase 3");
        initComponents();
        this.setSize(800,440);
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(0x646464));
        readTableFase3();
    }

    int numeroTentativas;

    boolean truePreenchido = false;
    boolean notPreenchido = false;
    boolean oitoPreenchido = false;
    boolean falsePreenchido = false;
    boolean samuelPreenchido = false;
    boolean snakePreenchido = false;
    boolean maxPreenchido = false;
    boolean cpuPreenchido = false;
    boolean floatPreenchido = false;
    boolean guidoPreenchido = false;
    boolean lowerPreenchido = false;
    boolean novePreenchido = false;
    boolean continuePreenchido = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        samuel1 = new javax.swing.JTextField();
        samuel2_max2 = new javax.swing.JTextField();
        samuel3 = new javax.swing.JTextField();
        samuel4_cpu3 = new javax.swing.JTextField();
        samuel5 = new javax.swing.JTextField();
        samuel6_float2 = new javax.swing.JTextField();
        max1 = new javax.swing.JTextField();
        max3 = new javax.swing.JTextField();
        cpu1 = new javax.swing.JTextField();
        cpu2 = new javax.swing.JTextField();
        float1_false1 = new javax.swing.JTextField();
        float3 = new javax.swing.JTextField();
        float4_snake3 = new javax.swing.JTextField();
        float5 = new javax.swing.JTextField();
        snake1 = new javax.swing.JTextField();
        snake2 = new javax.swing.JTextField();
        snake4 = new javax.swing.JTextField();
        snake5_lower4 = new javax.swing.JTextField();
        lower1_false3 = new javax.swing.JTextField();
        lower2 = new javax.swing.JTextField();
        lower5 = new javax.swing.JTextField();
        lower3 = new javax.swing.JTextField();
        false2 = new javax.swing.JTextField();
        false4 = new javax.swing.JTextField();
        false5_nove4 = new javax.swing.JTextField();
        nove1_not1 = new javax.swing.JTextField();
        nove2_oito4 = new javax.swing.JTextField();
        nove3 = new javax.swing.JTextField();
        oito1_guido5 = new javax.swing.JTextField();
        oito2 = new javax.swing.JTextField();
        oito3 = new javax.swing.JTextField();
        guido1 = new javax.swing.JTextField();
        guido2 = new javax.swing.JTextField();
        guido3 = new javax.swing.JTextField();
        guido4 = new javax.swing.JTextField();
        true1 = new javax.swing.JTextField();
        true2 = new javax.swing.JTextField();
        true3 = new javax.swing.JTextField();
        not2 = new javax.swing.JTextField();
        not3_continue4 = new javax.swing.JTextField();
        continue1 = new javax.swing.JTextField();
        continue2 = new javax.swing.JTextField();
        continue3 = new javax.swing.JTextField();
        continue5 = new javax.swing.JTextField();
        continue6 = new javax.swing.JTextField();
        continue7 = new javax.swing.JTextField();
        continue8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        respostaTextField = new javax.swing.JTextField();
        enviarButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fase3Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 100, 100));
        setPreferredSize(new java.awt.Dimension(800, 400));
        setSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        samuel1.setEditable(false);
        samuel1.setBackground(new java.awt.Color(255, 255, 255));
        samuel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        samuel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        samuel1.setToolTipText("");
        samuel1.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(samuel1);
        samuel1.setBounds(230, 50, 24, 21);

        samuel2_max2.setEditable(false);
        samuel2_max2.setBackground(new java.awt.Color(255, 255, 255));
        samuel2_max2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        samuel2_max2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        samuel2_max2.setToolTipText("");
        samuel2_max2.setPreferredSize(new java.awt.Dimension(24, 24));
        samuel2_max2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samuel2_max2ActionPerformed(evt);
            }
        });
        getContentPane().add(samuel2_max2);
        samuel2_max2.setBounds(230, 70, 24, 21);

        samuel3.setEditable(false);
        samuel3.setBackground(new java.awt.Color(255, 255, 255));
        samuel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        samuel3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        samuel3.setToolTipText("");
        samuel3.setPreferredSize(new java.awt.Dimension(24, 24));
        samuel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samuel3ActionPerformed(evt);
            }
        });
        getContentPane().add(samuel3);
        samuel3.setBounds(230, 90, 24, 21);

        samuel4_cpu3.setEditable(false);
        samuel4_cpu3.setBackground(new java.awt.Color(255, 255, 255));
        samuel4_cpu3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        samuel4_cpu3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        samuel4_cpu3.setToolTipText("");
        samuel4_cpu3.setPreferredSize(new java.awt.Dimension(24, 24));
        samuel4_cpu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samuel4_cpu3ActionPerformed(evt);
            }
        });
        getContentPane().add(samuel4_cpu3);
        samuel4_cpu3.setBounds(230, 110, 24, 21);

        samuel5.setEditable(false);
        samuel5.setBackground(new java.awt.Color(255, 255, 255));
        samuel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        samuel5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        samuel5.setToolTipText("");
        samuel5.setPreferredSize(new java.awt.Dimension(24, 24));
        samuel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samuel5ActionPerformed(evt);
            }
        });
        getContentPane().add(samuel5);
        samuel5.setBounds(230, 130, 24, 21);

        samuel6_float2.setEditable(false);
        samuel6_float2.setBackground(new java.awt.Color(255, 255, 255));
        samuel6_float2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        samuel6_float2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        samuel6_float2.setToolTipText("");
        samuel6_float2.setPreferredSize(new java.awt.Dimension(24, 24));
        samuel6_float2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samuel6_float2ActionPerformed(evt);
            }
        });
        getContentPane().add(samuel6_float2);
        samuel6_float2.setBounds(230, 150, 24, 21);

        max1.setEditable(false);
        max1.setBackground(new java.awt.Color(255, 255, 255));
        max1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        max1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        max1.setToolTipText("");
        max1.setPreferredSize(new java.awt.Dimension(24, 24));
        max1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                max1ActionPerformed(evt);
            }
        });
        getContentPane().add(max1);
        max1.setBounds(206, 70, 24, 21);

        max3.setEditable(false);
        max3.setBackground(new java.awt.Color(255, 255, 255));
        max3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        max3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        max3.setToolTipText("");
        max3.setPreferredSize(new java.awt.Dimension(24, 24));
        max3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                max3ActionPerformed(evt);
            }
        });
        getContentPane().add(max3);
        max3.setBounds(254, 70, 24, 21);

        cpu1.setEditable(false);
        cpu1.setBackground(new java.awt.Color(255, 255, 255));
        cpu1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        cpu1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpu1.setToolTipText("");
        cpu1.setPreferredSize(new java.awt.Dimension(24, 24));
        cpu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpu1ActionPerformed(evt);
            }
        });
        getContentPane().add(cpu1);
        cpu1.setBounds(206, 110, 24, 21);

        cpu2.setEditable(false);
        cpu2.setBackground(new java.awt.Color(255, 255, 255));
        cpu2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        cpu2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpu2.setToolTipText("");
        cpu2.setPreferredSize(new java.awt.Dimension(24, 24));
        cpu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpu2ActionPerformed(evt);
            }
        });
        getContentPane().add(cpu2);
        cpu2.setBounds(182, 110, 24, 21);

        float1_false1.setEditable(false);
        float1_false1.setBackground(new java.awt.Color(255, 255, 255));
        float1_false1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        float1_false1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        float1_false1.setToolTipText("");
        float1_false1.setPreferredSize(new java.awt.Dimension(24, 24));
        float1_false1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                float1_false1ActionPerformed(evt);
            }
        });
        getContentPane().add(float1_false1);
        float1_false1.setBounds(206, 150, 24, 21);

        float3.setEditable(false);
        float3.setBackground(new java.awt.Color(255, 255, 255));
        float3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        float3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        float3.setToolTipText("");
        float3.setPreferredSize(new java.awt.Dimension(24, 24));
        float3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                float3ActionPerformed(evt);
            }
        });
        getContentPane().add(float3);
        float3.setBounds(254, 150, 24, 21);

        float4_snake3.setEditable(false);
        float4_snake3.setBackground(new java.awt.Color(255, 255, 255));
        float4_snake3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        float4_snake3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        float4_snake3.setToolTipText("");
        float4_snake3.setPreferredSize(new java.awt.Dimension(24, 24));
        float4_snake3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                float4_snake3ActionPerformed(evt);
            }
        });
        getContentPane().add(float4_snake3);
        float4_snake3.setBounds(278, 150, 24, 21);

        float5.setEditable(false);
        float5.setBackground(new java.awt.Color(255, 255, 255));
        float5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        float5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        float5.setToolTipText("");
        float5.setPreferredSize(new java.awt.Dimension(24, 24));
        float5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                float5ActionPerformed(evt);
            }
        });
        getContentPane().add(float5);
        float5.setBounds(302, 150, 24, 21);

        snake1.setEditable(false);
        snake1.setBackground(new java.awt.Color(255, 255, 255));
        snake1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        snake1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        snake1.setToolTipText("");
        snake1.setPreferredSize(new java.awt.Dimension(24, 24));
        snake1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snake1ActionPerformed(evt);
            }
        });
        getContentPane().add(snake1);
        snake1.setBounds(278, 110, 24, 21);

        snake2.setEditable(false);
        snake2.setBackground(new java.awt.Color(255, 255, 255));
        snake2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        snake2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        snake2.setToolTipText("");
        snake2.setPreferredSize(new java.awt.Dimension(24, 24));
        snake2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snake2ActionPerformed(evt);
            }
        });
        getContentPane().add(snake2);
        snake2.setBounds(278, 130, 24, 21);

        snake4.setEditable(false);
        snake4.setBackground(new java.awt.Color(255, 255, 255));
        snake4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        snake4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        snake4.setToolTipText("");
        snake4.setPreferredSize(new java.awt.Dimension(24, 24));
        snake4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snake4ActionPerformed(evt);
            }
        });
        getContentPane().add(snake4);
        snake4.setBounds(278, 170, 24, 21);

        snake5_lower4.setEditable(false);
        snake5_lower4.setBackground(new java.awt.Color(255, 255, 255));
        snake5_lower4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        snake5_lower4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        snake5_lower4.setToolTipText("");
        snake5_lower4.setPreferredSize(new java.awt.Dimension(24, 24));
        snake5_lower4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snake5_lower4ActionPerformed(evt);
            }
        });
        getContentPane().add(snake5_lower4);
        snake5_lower4.setBounds(278, 190, 24, 21);

        lower1_false3.setEditable(false);
        lower1_false3.setBackground(new java.awt.Color(255, 255, 255));
        lower1_false3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lower1_false3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lower1_false3.setToolTipText("");
        lower1_false3.setPreferredSize(new java.awt.Dimension(24, 24));
        lower1_false3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lower1_false3ActionPerformed(evt);
            }
        });
        getContentPane().add(lower1_false3);
        lower1_false3.setBounds(206, 190, 24, 21);

        lower2.setEditable(false);
        lower2.setBackground(new java.awt.Color(255, 255, 255));
        lower2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lower2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lower2.setToolTipText("");
        lower2.setPreferredSize(new java.awt.Dimension(24, 24));
        lower2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lower2ActionPerformed(evt);
            }
        });
        getContentPane().add(lower2);
        lower2.setBounds(230, 190, 24, 21);

        lower5.setEditable(false);
        lower5.setBackground(new java.awt.Color(255, 255, 255));
        lower5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lower5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lower5.setToolTipText("");
        lower5.setPreferredSize(new java.awt.Dimension(24, 24));
        lower5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lower5ActionPerformed(evt);
            }
        });
        getContentPane().add(lower5);
        lower5.setBounds(302, 190, 24, 21);

        lower3.setEditable(false);
        lower3.setBackground(new java.awt.Color(255, 255, 255));
        lower3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lower3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lower3.setToolTipText("");
        lower3.setPreferredSize(new java.awt.Dimension(24, 24));
        lower3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lower3ActionPerformed(evt);
            }
        });
        getContentPane().add(lower3);
        lower3.setBounds(254, 190, 24, 21);

        false2.setEditable(false);
        false2.setBackground(new java.awt.Color(255, 255, 255));
        false2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        false2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        false2.setToolTipText("");
        false2.setPreferredSize(new java.awt.Dimension(24, 24));
        false2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                false2ActionPerformed(evt);
            }
        });
        getContentPane().add(false2);
        false2.setBounds(206, 170, 24, 21);

        false4.setEditable(false);
        false4.setBackground(new java.awt.Color(255, 255, 255));
        false4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        false4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        false4.setToolTipText("");
        false4.setPreferredSize(new java.awt.Dimension(24, 24));
        false4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                false4ActionPerformed(evt);
            }
        });
        getContentPane().add(false4);
        false4.setBounds(206, 210, 24, 21);

        false5_nove4.setEditable(false);
        false5_nove4.setBackground(new java.awt.Color(255, 255, 255));
        false5_nove4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        false5_nove4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        false5_nove4.setToolTipText("");
        false5_nove4.setPreferredSize(new java.awt.Dimension(24, 24));
        false5_nove4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                false5_nove4ActionPerformed(evt);
            }
        });
        getContentPane().add(false5_nove4);
        false5_nove4.setBounds(206, 230, 24, 21);

        nove1_not1.setEditable(false);
        nove1_not1.setBackground(new java.awt.Color(255, 255, 255));
        nove1_not1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        nove1_not1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nove1_not1.setToolTipText("");
        nove1_not1.setPreferredSize(new java.awt.Dimension(24, 24));
        nove1_not1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nove1_not1ActionPerformed(evt);
            }
        });
        getContentPane().add(nove1_not1);
        nove1_not1.setBounds(134, 230, 24, 21);

        nove2_oito4.setEditable(false);
        nove2_oito4.setBackground(new java.awt.Color(255, 255, 255));
        nove2_oito4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        nove2_oito4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nove2_oito4.setToolTipText("");
        nove2_oito4.setPreferredSize(new java.awt.Dimension(24, 24));
        nove2_oito4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nove2_oito4ActionPerformed(evt);
            }
        });
        getContentPane().add(nove2_oito4);
        nove2_oito4.setBounds(158, 230, 24, 21);

        nove3.setEditable(false);
        nove3.setBackground(new java.awt.Color(255, 255, 255));
        nove3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        nove3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nove3.setToolTipText("");
        nove3.setPreferredSize(new java.awt.Dimension(24, 24));
        nove3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nove3ActionPerformed(evt);
            }
        });
        getContentPane().add(nove3);
        nove3.setBounds(182, 230, 24, 21);

        oito1_guido5.setEditable(false);
        oito1_guido5.setBackground(new java.awt.Color(255, 255, 255));
        oito1_guido5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        oito1_guido5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oito1_guido5.setToolTipText("");
        oito1_guido5.setPreferredSize(new java.awt.Dimension(24, 24));
        oito1_guido5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oito1_guido5ActionPerformed(evt);
            }
        });
        getContentPane().add(oito1_guido5);
        oito1_guido5.setBounds(158, 170, 24, 21);

        oito2.setEditable(false);
        oito2.setBackground(new java.awt.Color(255, 255, 255));
        oito2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        oito2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oito2.setToolTipText("");
        oito2.setPreferredSize(new java.awt.Dimension(24, 24));
        oito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oito2ActionPerformed(evt);
            }
        });
        getContentPane().add(oito2);
        oito2.setBounds(158, 190, 24, 21);

        oito3.setEditable(false);
        oito3.setBackground(new java.awt.Color(255, 255, 255));
        oito3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        oito3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oito3.setToolTipText("");
        oito3.setPreferredSize(new java.awt.Dimension(24, 24));
        oito3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oito3ActionPerformed(evt);
            }
        });
        getContentPane().add(oito3);
        oito3.setBounds(158, 210, 24, 21);

        guido1.setEditable(false);
        guido1.setBackground(new java.awt.Color(255, 255, 255));
        guido1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        guido1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guido1.setToolTipText("");
        guido1.setPreferredSize(new java.awt.Dimension(24, 24));
        guido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guido1ActionPerformed(evt);
            }
        });
        getContentPane().add(guido1);
        guido1.setBounds(62, 170, 24, 21);

        guido2.setEditable(false);
        guido2.setBackground(new java.awt.Color(255, 255, 255));
        guido2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        guido2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guido2.setToolTipText("");
        guido2.setPreferredSize(new java.awt.Dimension(24, 24));
        guido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guido2ActionPerformed(evt);
            }
        });
        getContentPane().add(guido2);
        guido2.setBounds(86, 170, 24, 21);

        guido3.setEditable(false);
        guido3.setBackground(new java.awt.Color(255, 255, 255));
        guido3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        guido3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guido3.setToolTipText("");
        guido3.setPreferredSize(new java.awt.Dimension(24, 24));
        guido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guido3ActionPerformed(evt);
            }
        });
        getContentPane().add(guido3);
        guido3.setBounds(110, 170, 24, 21);

        guido4.setEditable(false);
        guido4.setBackground(new java.awt.Color(255, 255, 255));
        guido4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        guido4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guido4.setToolTipText("");
        guido4.setPreferredSize(new java.awt.Dimension(24, 24));
        guido4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guido4ActionPerformed(evt);
            }
        });
        getContentPane().add(guido4);
        guido4.setBounds(134, 170, 24, 21);

        true1.setEditable(false);
        true1.setBackground(new java.awt.Color(255, 255, 255));
        true1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        true1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        true1.setToolTipText("");
        true1.setPreferredSize(new java.awt.Dimension(24, 24));
        true1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                true1ActionPerformed(evt);
            }
        });
        getContentPane().add(true1);
        true1.setBounds(86, 130, 24, 21);

        true2.setEditable(false);
        true2.setBackground(new java.awt.Color(255, 255, 255));
        true2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        true2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        true2.setToolTipText("");
        true2.setPreferredSize(new java.awt.Dimension(24, 24));
        true2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                true2ActionPerformed(evt);
            }
        });
        getContentPane().add(true2);
        true2.setBounds(86, 150, 24, 21);

        true3.setEditable(false);
        true3.setBackground(new java.awt.Color(255, 255, 255));
        true3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        true3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        true3.setToolTipText("");
        true3.setPreferredSize(new java.awt.Dimension(24, 24));
        true3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                true3ActionPerformed(evt);
            }
        });
        getContentPane().add(true3);
        true3.setBounds(86, 190, 24, 21);

        not2.setEditable(false);
        not2.setBackground(new java.awt.Color(255, 255, 255));
        not2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        not2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        not2.setToolTipText("");
        not2.setPreferredSize(new java.awt.Dimension(24, 24));
        not2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                not2ActionPerformed(evt);
            }
        });
        getContentPane().add(not2);
        not2.setBounds(134, 250, 24, 21);

        not3_continue4.setEditable(false);
        not3_continue4.setBackground(new java.awt.Color(255, 255, 255));
        not3_continue4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        not3_continue4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        not3_continue4.setToolTipText("");
        not3_continue4.setPreferredSize(new java.awt.Dimension(24, 24));
        not3_continue4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                not3_continue4ActionPerformed(evt);
            }
        });
        getContentPane().add(not3_continue4);
        not3_continue4.setBounds(134, 270, 24, 21);

        continue1.setEditable(false);
        continue1.setBackground(new java.awt.Color(255, 255, 255));
        continue1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        continue1.setForeground(new java.awt.Color(255, 255, 255));
        continue1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        continue1.setToolTipText("");
        continue1.setPreferredSize(new java.awt.Dimension(24, 24));
        continue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue1ActionPerformed(evt);
            }
        });
        getContentPane().add(continue1);
        continue1.setBounds(62, 270, 24, 21);

        continue2.setEditable(false);
        continue2.setBackground(new java.awt.Color(255, 255, 255));
        continue2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        continue2.setForeground(new java.awt.Color(255, 255, 255));
        continue2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        continue2.setToolTipText("");
        continue2.setPreferredSize(new java.awt.Dimension(24, 24));
        continue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue2ActionPerformed(evt);
            }
        });
        getContentPane().add(continue2);
        continue2.setBounds(86, 270, 24, 21);

        continue3.setEditable(false);
        continue3.setBackground(new java.awt.Color(255, 255, 255));
        continue3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        continue3.setForeground(new java.awt.Color(255, 255, 255));
        continue3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        continue3.setToolTipText("");
        continue3.setPreferredSize(new java.awt.Dimension(24, 24));
        continue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue3ActionPerformed(evt);
            }
        });
        getContentPane().add(continue3);
        continue3.setBounds(110, 270, 24, 21);

        continue5.setEditable(false);
        continue5.setBackground(new java.awt.Color(255, 255, 255));
        continue5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        continue5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        continue5.setToolTipText("");
        continue5.setPreferredSize(new java.awt.Dimension(24, 24));
        continue5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue5ActionPerformed(evt);
            }
        });
        getContentPane().add(continue5);
        continue5.setBounds(158, 270, 24, 21);

        continue6.setEditable(false);
        continue6.setBackground(new java.awt.Color(255, 255, 255));
        continue6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        continue6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        continue6.setToolTipText("");
        continue6.setPreferredSize(new java.awt.Dimension(24, 24));
        continue6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue6ActionPerformed(evt);
            }
        });
        getContentPane().add(continue6);
        continue6.setBounds(182, 270, 24, 21);

        continue7.setEditable(false);
        continue7.setBackground(new java.awt.Color(255, 255, 255));
        continue7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        continue7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        continue7.setToolTipText("");
        continue7.setPreferredSize(new java.awt.Dimension(24, 24));
        continue7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue7ActionPerformed(evt);
            }
        });
        getContentPane().add(continue7);
        continue7.setBounds(206, 270, 24, 21);

        continue8.setEditable(false);
        continue8.setBackground(new java.awt.Color(255, 255, 255));
        continue8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        continue8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        continue8.setToolTipText("");
        continue8.setPreferredSize(new java.awt.Dimension(24, 24));
        continue8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue8ActionPerformed(evt);
            }
        });
        getContentPane().add(continue8);
        continue8.setBounds(230, 270, 24, 21);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("26");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 130, 20, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("23");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 110, 20, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("27");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 30, 20, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("28");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 90, 20, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("29");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 70, 20, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("30");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 110, 20, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("31");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 150, 20, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("33");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 190, 20, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("32");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 170, 20, 16);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("34");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 230, 20, 16);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("35");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 270, 20, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("25");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(160, 150, 20, 16);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("24");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(140, 210, 20, 16);

        respostaTextField.setBackground(new java.awt.Color(255, 232, 115));
        respostaTextField.setMargin(new java.awt.Insets(6, 6, 2, 6));
        respostaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(respostaTextField);
        respostaTextField.setBounds(40, 340, 210, 30);

        enviarButton.setBackground(new java.awt.Color(255, 212, 59));
        enviarButton.setForeground(new java.awt.Color(255, 255, 255));
        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enviarButton);
        enviarButton.setBounds(270, 340, 72, 30);

        sairButton.setBackground(new java.awt.Color(48, 105, 152));
        sairButton.setForeground(new java.awt.Color(255, 255, 255));
        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton);
        sairButton.setBounds(10, 10, 60, 22);

        jScrollPane1.setBackground(new java.awt.Color(100, 100, 100));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        fase3Table.setBackground(new java.awt.Color(100, 100, 100));
        fase3Table.setForeground(new java.awt.Color(255, 255, 255));
        fase3Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Dica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fase3Table.setRowHeight(40);
        fase3Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(fase3Table);
        if (fase3Table.getColumnModel().getColumnCount() > 0) {
            fase3Table.getColumnModel().getColumn(0).setResizable(false);
            fase3Table.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 10, 390, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void samuel2_max2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samuel2_max2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samuel2_max2ActionPerformed

    private void samuel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samuel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samuel3ActionPerformed

    private void samuel4_cpu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samuel4_cpu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samuel4_cpu3ActionPerformed

    private void samuel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samuel5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samuel5ActionPerformed

    private void samuel6_float2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samuel6_float2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samuel6_float2ActionPerformed

    private void max1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_max1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_max1ActionPerformed

    private void max3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_max3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_max3ActionPerformed

    private void cpu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpu1ActionPerformed

    private void cpu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpu2ActionPerformed

    private void float3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_float3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_float3ActionPerformed

    private void float1_false1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_float1_false1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_float1_false1ActionPerformed

    private void float4_snake3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_float4_snake3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_float4_snake3ActionPerformed

    private void float5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_float5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_float5ActionPerformed

    private void snake1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snake1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snake1ActionPerformed

    private void snake2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snake2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snake2ActionPerformed

    private void snake4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snake4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snake4ActionPerformed

    private void snake5_lower4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snake5_lower4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snake5_lower4ActionPerformed

    private void lower1_false3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lower1_false3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lower1_false3ActionPerformed

    private void lower2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lower2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lower2ActionPerformed

    private void lower5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lower5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lower5ActionPerformed

    private void lower3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lower3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lower3ActionPerformed

    private void false2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_false2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_false2ActionPerformed

    private void false4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_false4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_false4ActionPerformed

    private void false5_nove4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_false5_nove4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_false5_nove4ActionPerformed

    private void guido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guido1ActionPerformed

    private void true1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_true1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_true1ActionPerformed

    private void nove1_not1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nove1_not1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nove1_not1ActionPerformed

    private void oito1_guido5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oito1_guido5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oito1_guido5ActionPerformed

    private void nove2_oito4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nove2_oito4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nove2_oito4ActionPerformed

    private void nove3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nove3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nove3ActionPerformed

    private void oito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oito2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oito2ActionPerformed

    private void oito3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oito3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oito3ActionPerformed

    private void guido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guido3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guido3ActionPerformed

    private void guido4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guido4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guido4ActionPerformed

    private void guido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guido2ActionPerformed

    private void true2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_true2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_true2ActionPerformed

    private void true3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_true3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_true3ActionPerformed

    private void not2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_not2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_not2ActionPerformed

    private void not3_continue4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_not3_continue4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_not3_continue4ActionPerformed

    private void continue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continue1ActionPerformed

    private void continue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continue2ActionPerformed

    private void continue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continue3ActionPerformed

    private void continue5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continue5ActionPerformed

    private void continue6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continue6ActionPerformed

    private void continue7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continue7ActionPerformed

    private void continue8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continue8ActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        if (!"".equals(respostaTextField.getText().toLowerCase())) {
            numeroTentativas += 1;
            PalavraDAO dao = new PalavraDAO();
            if (dao.verificarRespostaFase3(respostaTextField.getText().toLowerCase())) {
                switch (respostaTextField.getText().toLowerCase()) {
                    case "true":
                        if (!truePreenchido) {
                            preencherTrue();
                            truePreenchido = true;
                        }
                        break;
                    case "not":
                        if (!notPreenchido) {
                            preencherNot();
                            notPreenchido = true;
                        }
                        break;
                    case "oito":
                        if (!oitoPreenchido) {
                            preencherOito();
                            oitoPreenchido = true;
                        }
                        break;
                    case "false":
                        if (!falsePreenchido) {
                            preencherFalse();
                            falsePreenchido = true;
                        }
                        break;
                    case "samuel":
                        if (!samuelPreenchido) {
                            preencherSamuel();
                            samuelPreenchido = true;
                        }
                        break;
                    case "snake":
                        if (!snakePreenchido) {
                            preencherSnake();
                            snakePreenchido = true;
                        }
                        break;
                    case "max":
                        if (!maxPreenchido) {
                            preencherMax();
                            maxPreenchido = true;
                        }
                        break;
                    case "cpu":
                        if (!cpuPreenchido) {
                            preencherCpu();
                            cpuPreenchido = true;
                        }
                        break;
                    case "float":
                        if (!floatPreenchido) {
                            preencherFloat();
                            floatPreenchido = true;
                        }
                        break;
                    case "guido":
                        if (!guidoPreenchido) {
                            preencherGuido();
                            guidoPreenchido = true;
                        }
                        break;
                    case "lower":
                        if (!lowerPreenchido) {
                            preencherLower();
                            lowerPreenchido = true;
                        }
                        break;
                    case "nove":
                        if (!novePreenchido) {
                            preencherNove();
                            novePreenchido = true;
                        }
                        break;
                    case "continue":
                        if (!continuePreenchido) {
                            preencherContinue();
                            continuePreenchido = true;
                        }
                        break;
                }
                if (truePreenchido && notPreenchido && oitoPreenchido && falsePreenchido && samuelPreenchido && snakePreenchido && maxPreenchido && cpuPreenchido && floatPreenchido && guidoPreenchido && lowerPreenchido && novePreenchido && continuePreenchido) {
                    UsuarioDAO udao = new UsuarioDAO();
                    String jogadorAtual = TelaLogin.getJogadorAtual();
                    if (!udao.fase3Completa(jogadorAtual)) {
                        udao.updatePontuacao(jogadorAtual, calcularPontuacao());
                        udao.updateFase3Completa(jogadorAtual);
                    }
                    JOptionPane.showMessageDialog(null, "Parabéns! Você acertou todas as palavras!");
                    MenuInicial mi = new MenuInicial();
                    mi.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Resposta errada!");
            }
            respostaTextField.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Insira uma palavra no campo de resposta antes de enviar.");
        }

    }//GEN-LAST:event_enviarButtonActionPerformed

    private void respostaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respostaTextFieldActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        MenuInicial mi = new MenuInicial();
        mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fase3().setVisible(true);
            }
        });
    }

    private void readTableFase3() {
        fase3Table.getColumnModel().getColumn(0).setPreferredWidth(40);
        fase3Table.getColumnModel().getColumn(1).setPreferredWidth(300);
        
        DefaultTableModel model = (DefaultTableModel) fase3Table.getModel();
        model.setNumRows(0);

        PalavraDAO dao = new PalavraDAO();

        for (Palavra p : dao.readPalavrasFase3()) {
            Object[] dados = {p.getId(), p.getDica()};
            model.addRow(dados);
        }
    }

    private int calcularPontuacao() {
        double a = 13.0 / numeroTentativas * 100;
        int b = (int) Math.round(a);
        return b;
    }

    public void preencherTrue() {
        true1.setText("t");
        true2.setText("r");
        guido2.setText("u");
        true3.setText("e");
    }

    public void preencherNot() {
        nove1_not1.setText("n");
        not2.setText("o");
        not3_continue4.setText("t");
    }

    public void preencherOito() {
        oito1_guido5.setText("o");
        oito2.setText("i");
        oito3.setText("t");
        nove2_oito4.setText("o");

    }

    public void preencherFalse() {
        float1_false1.setText("f");
        false2.setText("a");
        lower1_false3.setText("l");
        false4.setText("s");
        false5_nove4.setText("e");
    }

    public void preencherSamuel() {
        samuel1.setText("s");
        samuel2_max2.setText("a");
        samuel3.setText("m");
        samuel4_cpu3.setText("u");
        samuel5.setText("e");
        samuel6_float2.setText("l");
    }

    public void preencherSnake() {
        snake1.setText("s");
        snake2.setText("n");
        float4_snake3.setText("a");
        snake4.setText("k");
        snake5_lower4.setText("e");
    }

    public void preencherMax() {
        max1.setText("m");
        samuel2_max2.setText("a");
        max3.setText("x");
    }

    public void preencherCpu() {
        cpu1.setText("c");
        cpu2.setText("p");
        samuel4_cpu3.setText("u");
    }

    public void preencherFloat() {
        float1_false1.setText("f");
        samuel6_float2.setText("l");
        float3.setText("o");
        float4_snake3.setText("a");
        float5.setText("t");
    }

    public void preencherGuido() {
        guido1.setText("g");
        guido2.setText("u");
        guido3.setText("i");
        guido4.setText("d");
        oito1_guido5.setText("o");
    }

    public void preencherLower() {
        lower1_false3.setText("l");
        lower2.setText("o");
        lower3.setText("w");
        snake5_lower4.setText("e");
        lower5.setText("r");
    }

    public void preencherNove() {
        nove1_not1.setText("n");
        nove2_oito4.setText("o");
        nove3.setText("v");
        false5_nove4.setText("e");
    }

    public void preencherContinue() {
        continue1.setText("c");
        continue2.setText("o");
        continue3.setText("n");
        not3_continue4.setText("t");
        continue5.setText("i");
        continue6.setText("n");
        continue7.setText("u");
        continue8.setText("e");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField continue1;
    private javax.swing.JTextField continue2;
    private javax.swing.JTextField continue3;
    private javax.swing.JTextField continue5;
    private javax.swing.JTextField continue6;
    private javax.swing.JTextField continue7;
    private javax.swing.JTextField continue8;
    private javax.swing.JTextField cpu1;
    private javax.swing.JTextField cpu2;
    private javax.swing.JButton enviarButton;
    private javax.swing.JTextField false2;
    private javax.swing.JTextField false4;
    private javax.swing.JTextField false5_nove4;
    private javax.swing.JTable fase3Table;
    private javax.swing.JTextField float1_false1;
    private javax.swing.JTextField float3;
    private javax.swing.JTextField float4_snake3;
    private javax.swing.JTextField float5;
    private javax.swing.JTextField guido1;
    private javax.swing.JTextField guido2;
    private javax.swing.JTextField guido3;
    private javax.swing.JTextField guido4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lower1_false3;
    private javax.swing.JTextField lower2;
    private javax.swing.JTextField lower3;
    private javax.swing.JTextField lower5;
    private javax.swing.JTextField max1;
    private javax.swing.JTextField max3;
    private javax.swing.JTextField not2;
    private javax.swing.JTextField not3_continue4;
    private javax.swing.JTextField nove1_not1;
    private javax.swing.JTextField nove2_oito4;
    private javax.swing.JTextField nove3;
    private javax.swing.JTextField oito1_guido5;
    private javax.swing.JTextField oito2;
    private javax.swing.JTextField oito3;
    private javax.swing.JTextField respostaTextField;
    private javax.swing.JButton sairButton;
    private javax.swing.JTextField samuel1;
    private javax.swing.JTextField samuel2_max2;
    private javax.swing.JTextField samuel3;
    private javax.swing.JTextField samuel4_cpu3;
    private javax.swing.JTextField samuel5;
    private javax.swing.JTextField samuel6_float2;
    private javax.swing.JTextField snake1;
    private javax.swing.JTextField snake2;
    private javax.swing.JTextField snake4;
    private javax.swing.JTextField snake5_lower4;
    private javax.swing.JTextField true1;
    private javax.swing.JTextField true2;
    private javax.swing.JTextField true3;
    // End of variables declaration//GEN-END:variables
}
