/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Palavra;
import model.dao.PalavraDAO;
import model.dao.UsuarioDAO;

/**
 *
 * @author Enrico
 */
public class Fase1 extends javax.swing.JFrame {

    /**
     * Creates new form Fase2
     */
    public Fase1() {
        super("Fase 1");
        initComponents();
        this.setSize(860,440);
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(0x646464));
        readTableFase1();
    }

    int numeroTentativas;

    boolean interpretadaPreenchido = false;
    boolean inputPreenchido = false;
    boolean printPreenchido = false;
    boolean turtlePreenchido = false;
    boolean hashtagPreenchido = false;
    boolean lenPreenchido = false;
    boolean colchetePreenchido = false;
    boolean importPreenchido = false;
    boolean returnPreenchido = false;
    boolean variavelPreenchido = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        interpretada1 = new javax.swing.JTextField();
        interpretada2_len3 = new javax.swing.JTextField();
        interpretada3 = new javax.swing.JTextField();
        interpretada4_colchete8 = new javax.swing.JTextField();
        interpretada5 = new javax.swing.JTextField();
        interpretada6 = new javax.swing.JTextField();
        interpretada7_return1 = new javax.swing.JTextField();
        interpretada8 = new javax.swing.JTextField();
        interpretada9 = new javax.swing.JTextField();
        interpretada10_variavel5 = new javax.swing.JTextField();
        interpretada11 = new javax.swing.JTextField();
        interpretada12 = new javax.swing.JTextField();
        len1 = new javax.swing.JTextField();
        len2 = new javax.swing.JTextField();
        colchete1 = new javax.swing.JTextField();
        colchete2 = new javax.swing.JTextField();
        colchete3 = new javax.swing.JTextField();
        colchete4 = new javax.swing.JTextField();
        colchete5 = new javax.swing.JTextField();
        colchete6 = new javax.swing.JTextField();
        colchete7 = new javax.swing.JTextField();
        return5 = new javax.swing.JTextField();
        return4_input4 = new javax.swing.JTextField();
        return6_print4 = new javax.swing.JTextField();
        return2 = new javax.swing.JTextField();
        return3 = new javax.swing.JTextField();
        variavel1 = new javax.swing.JTextField();
        variavel2 = new javax.swing.JTextField();
        variavel3 = new javax.swing.JTextField();
        variavel4 = new javax.swing.JTextField();
        variavel6 = new javax.swing.JTextField();
        variavel7 = new javax.swing.JTextField();
        variavel8 = new javax.swing.JTextField();
        input3 = new javax.swing.JTextField();
        input2 = new javax.swing.JTextField();
        input5 = new javax.swing.JTextField();
        print2 = new javax.swing.JTextField();
        print3 = new javax.swing.JTextField();
        print5 = new javax.swing.JTextField();
        import1 = new javax.swing.JTextField();
        import2 = new javax.swing.JTextField();
        import3_print1 = new javax.swing.JTextField();
        import4 = new javax.swing.JTextField();
        import5 = new javax.swing.JTextField();
        import6_turtle4 = new javax.swing.JTextField();
        turtle2 = new javax.swing.JTextField();
        turtle3 = new javax.swing.JTextField();
        turtle5 = new javax.swing.JTextField();
        turtle6 = new javax.swing.JTextField();
        hashtag1 = new javax.swing.JTextField();
        hashtag2 = new javax.swing.JTextField();
        hashtag3 = new javax.swing.JTextField();
        hashtag4 = new javax.swing.JTextField();
        hashtag5_turtle1 = new javax.swing.JTextField();
        hashtag6 = new javax.swing.JTextField();
        hashtag7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fase1Table = new javax.swing.JTable();
        respostaTextField = new javax.swing.JTextField();
        enviarButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));
        setSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        interpretada1.setEditable(false);
        interpretada1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada1.setToolTipText("");
        interpretada1.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada1ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada1);
        interpretada1.setBounds(210, 40, 24, 24);

        interpretada2_len3.setEditable(false);
        interpretada2_len3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada2_len3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada2_len3.setToolTipText("");
        interpretada2_len3.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada2_len3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada2_len3ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada2_len3);
        interpretada2_len3.setBounds(210, 60, 24, 24);

        interpretada3.setEditable(false);
        interpretada3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada3.setToolTipText("");
        interpretada3.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada3ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada3);
        interpretada3.setBounds(210, 80, 24, 24);

        interpretada4_colchete8.setEditable(false);
        interpretada4_colchete8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada4_colchete8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada4_colchete8.setToolTipText("");
        interpretada4_colchete8.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada4_colchete8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada4_colchete8ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada4_colchete8);
        interpretada4_colchete8.setBounds(210, 100, 24, 24);

        interpretada5.setEditable(false);
        interpretada5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada5.setToolTipText("");
        interpretada5.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada5ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada5);
        interpretada5.setBounds(210, 120, 24, 24);

        interpretada6.setEditable(false);
        interpretada6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada6.setToolTipText("");
        interpretada6.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada6ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada6);
        interpretada6.setBounds(210, 140, 24, 24);

        interpretada7_return1.setEditable(false);
        interpretada7_return1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada7_return1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada7_return1.setToolTipText("");
        interpretada7_return1.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada7_return1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada7_return1ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada7_return1);
        interpretada7_return1.setBounds(210, 160, 24, 24);

        interpretada8.setEditable(false);
        interpretada8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada8.setToolTipText("");
        interpretada8.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada8ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada8);
        interpretada8.setBounds(210, 180, 24, 24);

        interpretada9.setEditable(false);
        interpretada9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada9.setToolTipText("");
        interpretada9.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada9ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada9);
        interpretada9.setBounds(210, 200, 24, 24);

        interpretada10_variavel5.setEditable(false);
        interpretada10_variavel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada10_variavel5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada10_variavel5.setToolTipText("");
        interpretada10_variavel5.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada10_variavel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada10_variavel5ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada10_variavel5);
        interpretada10_variavel5.setBounds(210, 220, 24, 24);

        interpretada11.setEditable(false);
        interpretada11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada11.setToolTipText("");
        interpretada11.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada11ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada11);
        interpretada11.setBounds(210, 240, 24, 24);

        interpretada12.setEditable(false);
        interpretada12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        interpretada12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interpretada12.setToolTipText("");
        interpretada12.setPreferredSize(new java.awt.Dimension(24, 24));
        interpretada12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpretada12ActionPerformed(evt);
            }
        });
        getContentPane().add(interpretada12);
        interpretada12.setBounds(210, 260, 24, 24);

        len1.setEditable(false);
        len1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        len1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        len1.setToolTipText("");
        len1.setPreferredSize(new java.awt.Dimension(24, 24));
        len1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                len1ActionPerformed(evt);
            }
        });
        getContentPane().add(len1);
        len1.setBounds(166, 63, 24, 21);

        len2.setEditable(false);
        len2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        len2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        len2.setToolTipText("");
        len2.setPreferredSize(new java.awt.Dimension(24, 24));
        len2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                len2ActionPerformed(evt);
            }
        });
        getContentPane().add(len2);
        len2.setBounds(190, 63, 24, 21);

        colchete1.setEditable(false);
        colchete1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        colchete1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colchete1.setToolTipText("");
        colchete1.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(colchete1);
        colchete1.setBounds(44, 103, 24, 21);

        colchete2.setEditable(false);
        colchete2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        colchete2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colchete2.setToolTipText("");
        colchete2.setPreferredSize(new java.awt.Dimension(24, 24));
        colchete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colchete2ActionPerformed(evt);
            }
        });
        getContentPane().add(colchete2);
        colchete2.setBounds(68, 103, 24, 21);

        colchete3.setEditable(false);
        colchete3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        colchete3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colchete3.setToolTipText("");
        colchete3.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(colchete3);
        colchete3.setBounds(92, 103, 24, 21);

        colchete4.setEditable(false);
        colchete4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        colchete4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colchete4.setToolTipText("");
        colchete4.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(colchete4);
        colchete4.setBounds(116, 103, 24, 21);

        colchete5.setEditable(false);
        colchete5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        colchete5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colchete5.setToolTipText("");
        colchete5.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(colchete5);
        colchete5.setBounds(140, 103, 24, 21);

        colchete6.setEditable(false);
        colchete6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        colchete6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colchete6.setToolTipText("");
        colchete6.setPreferredSize(new java.awt.Dimension(24, 24));
        colchete6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colchete6ActionPerformed(evt);
            }
        });
        getContentPane().add(colchete6);
        colchete6.setBounds(162, 103, 24, 21);

        colchete7.setEditable(false);
        colchete7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        colchete7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colchete7.setToolTipText("");
        colchete7.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(colchete7);
        colchete7.setBounds(186, 103, 24, 21);

        return5.setEditable(false);
        return5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        return5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        return5.setToolTipText("");
        return5.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(return5);
        return5.setBounds(306, 163, 24, 21);

        return4_input4.setEditable(false);
        return4_input4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        return4_input4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        return4_input4.setToolTipText("");
        return4_input4.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(return4_input4);
        return4_input4.setBounds(282, 163, 24, 21);

        return6_print4.setEditable(false);
        return6_print4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        return6_print4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        return6_print4.setToolTipText("");
        return6_print4.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(return6_print4);
        return6_print4.setBounds(330, 163, 24, 21);

        return2.setEditable(false);
        return2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        return2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        return2.setToolTipText("");
        return2.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(return2);
        return2.setBounds(234, 163, 24, 21);

        return3.setEditable(false);
        return3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        return3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        return3.setToolTipText("");
        return3.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(return3);
        return3.setBounds(258, 163, 24, 21);

        variavel1.setEditable(false);
        variavel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        variavel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        variavel1.setToolTipText("");
        variavel1.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(variavel1);
        variavel1.setBounds(114, 223, 24, 21);

        variavel2.setEditable(false);
        variavel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        variavel2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        variavel2.setToolTipText("");
        variavel2.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(variavel2);
        variavel2.setBounds(138, 223, 24, 21);

        variavel3.setEditable(false);
        variavel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        variavel3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        variavel3.setToolTipText("");
        variavel3.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(variavel3);
        variavel3.setBounds(162, 223, 24, 21);

        variavel4.setEditable(false);
        variavel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        variavel4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        variavel4.setToolTipText("");
        variavel4.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(variavel4);
        variavel4.setBounds(186, 223, 24, 21);

        variavel6.setEditable(false);
        variavel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        variavel6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        variavel6.setToolTipText("");
        variavel6.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(variavel6);
        variavel6.setBounds(234, 223, 24, 21);

        variavel7.setEditable(false);
        variavel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        variavel7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        variavel7.setToolTipText("");
        variavel7.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(variavel7);
        variavel7.setBounds(258, 223, 24, 21);

        variavel8.setEditable(false);
        variavel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        variavel8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        variavel8.setToolTipText("");
        variavel8.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(variavel8);
        variavel8.setBounds(282, 223, 24, 21);

        input3.setEditable(false);
        input3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        input3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input3.setToolTipText("");
        input3.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(input3);
        input3.setBounds(282, 142, 24, 21);

        input2.setEditable(false);
        input2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        input2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input2.setToolTipText("");
        input2.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(input2);
        input2.setBounds(282, 122, 24, 21);

        input5.setEditable(false);
        input5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        input5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input5.setToolTipText("");
        input5.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(input5);
        input5.setBounds(282, 184, 24, 21);

        print2.setEditable(false);
        print2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        print2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        print2.setToolTipText("");
        print2.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(print2);
        print2.setBounds(330, 122, 24, 21);

        print3.setEditable(false);
        print3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        print3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        print3.setToolTipText("");
        print3.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(print3);
        print3.setBounds(330, 142, 24, 21);

        print5.setEditable(false);
        print5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        print5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        print5.setToolTipText("");
        print5.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(print5);
        print5.setBounds(330, 184, 24, 21);

        import1.setEditable(false);
        import1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        import1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        import1.setToolTipText("");
        import1.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(import1);
        import1.setBounds(282, 102, 24, 21);

        import2.setEditable(false);
        import2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        import2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        import2.setToolTipText("");
        import2.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(import2);
        import2.setBounds(306, 102, 24, 21);

        import3_print1.setEditable(false);
        import3_print1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        import3_print1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        import3_print1.setToolTipText("");
        import3_print1.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(import3_print1);
        import3_print1.setBounds(330, 102, 24, 21);

        import4.setEditable(false);
        import4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        import4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        import4.setToolTipText("");
        import4.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(import4);
        import4.setBounds(354, 102, 24, 21);

        import5.setEditable(false);
        import5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        import5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        import5.setToolTipText("");
        import5.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(import5);
        import5.setBounds(378, 102, 24, 21);

        import6_turtle4.setEditable(false);
        import6_turtle4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        import6_turtle4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        import6_turtle4.setToolTipText("");
        import6_turtle4.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(import6_turtle4);
        import6_turtle4.setBounds(402, 102, 24, 21);

        turtle2.setEditable(false);
        turtle2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        turtle2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        turtle2.setToolTipText("");
        turtle2.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(turtle2);
        turtle2.setBounds(402, 62, 24, 21);

        turtle3.setEditable(false);
        turtle3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        turtle3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        turtle3.setToolTipText("");
        turtle3.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(turtle3);
        turtle3.setBounds(402, 82, 24, 21);

        turtle5.setEditable(false);
        turtle5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        turtle5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        turtle5.setToolTipText("");
        turtle5.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(turtle5);
        turtle5.setBounds(402, 122, 24, 21);

        turtle6.setEditable(false);
        turtle6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        turtle6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        turtle6.setToolTipText("");
        turtle6.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(turtle6);
        turtle6.setBounds(402, 142, 24, 21);

        hashtag1.setEditable(false);
        hashtag1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        hashtag1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hashtag1.setToolTipText("");
        hashtag1.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(hashtag1);
        hashtag1.setBounds(308, 42, 24, 21);

        hashtag2.setEditable(false);
        hashtag2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        hashtag2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hashtag2.setToolTipText("");
        hashtag2.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(hashtag2);
        hashtag2.setBounds(332, 42, 24, 21);

        hashtag3.setEditable(false);
        hashtag3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        hashtag3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hashtag3.setToolTipText("");
        hashtag3.setPreferredSize(new java.awt.Dimension(24, 24));
        hashtag3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashtag3ActionPerformed(evt);
            }
        });
        getContentPane().add(hashtag3);
        hashtag3.setBounds(356, 42, 24, 21);

        hashtag4.setEditable(false);
        hashtag4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        hashtag4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hashtag4.setToolTipText("");
        hashtag4.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(hashtag4);
        hashtag4.setBounds(380, 42, 24, 21);

        hashtag5_turtle1.setEditable(false);
        hashtag5_turtle1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        hashtag5_turtle1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hashtag5_turtle1.setToolTipText("");
        hashtag5_turtle1.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(hashtag5_turtle1);
        hashtag5_turtle1.setBounds(402, 42, 24, 21);

        hashtag6.setEditable(false);
        hashtag6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        hashtag6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hashtag6.setToolTipText("");
        hashtag6.setPreferredSize(new java.awt.Dimension(24, 24));
        getContentPane().add(hashtag6);
        hashtag6.setBounds(426, 42, 24, 21);

        hashtag7.setEditable(false);
        hashtag7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        hashtag7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hashtag7.setToolTipText("");
        hashtag7.setPreferredSize(new java.awt.Dimension(24, 24));
        hashtag7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashtag7ActionPerformed(evt);
            }
        });
        getContentPane().add(hashtag7);
        hashtag7.setBounds(450, 42, 24, 21);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("10");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 220, 20, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 20, 10, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("6");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 60, 10, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("7");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 100, 10, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 30, 10, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("4");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 20, 10, 16);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("8");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 100, 10, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("3");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 80, 10, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("2");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 80, 10, 16);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("9");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 160, 10, 16);

        fase1Table.setBackground(new java.awt.Color(100, 100, 100));
        fase1Table.setForeground(new java.awt.Color(255, 255, 255));
        fase1Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Dica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fase1Table.setRowHeight(40);
        fase1Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(fase1Table);
        if (fase1Table.getColumnModel().getColumnCount() > 0) {
            fase1Table.getColumnModel().getColumn(0).setResizable(false);
            fase1Table.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(480, 10, 360, 380);

        respostaTextField.setBackground(new java.awt.Color(255, 232, 115));
        respostaTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        respostaTextField.setBorder(null);
        respostaTextField.setMargin(new java.awt.Insets(6, 6, 2, 6));
        respostaTextField.setMinimumSize(new java.awt.Dimension(64, 39));
        respostaTextField.setPreferredSize(new java.awt.Dimension(64, 39));
        respostaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(respostaTextField);
        respostaTextField.setBounds(100, 320, 200, 30);

        enviarButton.setBackground(new java.awt.Color(255, 212, 59));
        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enviarButton);
        enviarButton.setBounds(320, 320, 72, 30);

        sairButton.setBackground(new java.awt.Color(48, 105, 152));
        sairButton.setForeground(new java.awt.Color(255, 255, 255));
        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton);
        sairButton.setBounds(10, 10, 60, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void interpretada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada1ActionPerformed

    private void interpretada2_len3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada2_len3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada2_len3ActionPerformed

    private void interpretada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada3ActionPerformed

    private void interpretada4_colchete8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada4_colchete8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada4_colchete8ActionPerformed

    private void interpretada5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada5ActionPerformed

    private void interpretada6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada6ActionPerformed

    private void interpretada7_return1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada7_return1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada7_return1ActionPerformed

    private void interpretada8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada8ActionPerformed

    private void interpretada9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada9ActionPerformed

    private void interpretada10_variavel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada10_variavel5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada10_variavel5ActionPerformed

    private void interpretada11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada11ActionPerformed

    private void interpretada12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpretada12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interpretada12ActionPerformed

    private void len2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_len2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_len2ActionPerformed

    private void len1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_len1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_len1ActionPerformed

    private void colchete6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colchete6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colchete6ActionPerformed

    private void colchete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colchete2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colchete2ActionPerformed

    private void hashtag3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashtag3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hashtag3ActionPerformed

    private void hashtag7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashtag7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hashtag7ActionPerformed

    private void respostaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaTextFieldActionPerformed

    }//GEN-LAST:event_respostaTextFieldActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        if (!"".equals(respostaTextField.getText().toLowerCase())) {
            numeroTentativas += 1;
            PalavraDAO pdao = new PalavraDAO();
            if (pdao.verificarRespostaFase1(respostaTextField.getText().toLowerCase())) {
                switch (respostaTextField.getText().toLowerCase()) {
                    case "interpretada":
                        if (!interpretadaPreenchido) {
                            preencherInterpretada();
                            interpretadaPreenchido = true;
                        }
                        break;
                    case "input":
                        if (!inputPreenchido) {
                            preencherInput();
                            inputPreenchido = true;
                        }
                        break;
                    case "print":
                        if (!printPreenchido) {
                            preencherPrint();
                            printPreenchido = true;
                        }
                        break;
                    case "turtle":
                        if (!turtlePreenchido) {
                            preencherTurtle();
                            turtlePreenchido = true;
                        }
                        break;
                    case "hashtag":
                        if (!hashtagPreenchido) {
                            preencherHashtag();
                            hashtagPreenchido = true;
                        }
                        break;
                    case "len":
                        if (!lenPreenchido) {
                            preencherLen();
                            lenPreenchido = true;
                        }
                        break;
                    case "colchete":
                        if (!colchetePreenchido) {
                            preencherColchete();
                            colchetePreenchido = true;
                        }
                        break;
                    case "import":
                        if (!importPreenchido) {
                            preencherImport();
                            importPreenchido = true;
                        }
                        break;
                    case "return":
                        if (!returnPreenchido) {
                            preencherReturn();
                            returnPreenchido = true;
                        }
                        break;
                    case "variavel":
                        if (!variavelPreenchido) {
                            preencherVariavel();
                            variavelPreenchido = true;
                        }
                        break;
                }

                if (interpretadaPreenchido && inputPreenchido && printPreenchido && turtlePreenchido && hashtagPreenchido && lenPreenchido && colchetePreenchido && importPreenchido && returnPreenchido && variavelPreenchido) {
                    UsuarioDAO udao = new UsuarioDAO();
                    String jogadorAtual = TelaLogin.getJogadorAtual();
                    if (!udao.fase1Completa(jogadorAtual)) {
                        udao.updatePontuacao(jogadorAtual, calcularPontuacao());
                        udao.updateFase1Completa(jogadorAtual);
                    }
                    JOptionPane.showMessageDialog(null, "Parabéns! Você acertou todas as palavras!");
                    MenuInicial mi = new MenuInicial();
                    mi.setVisible(true);
                    this.dispose();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Resposta incorreta!");
            }
            respostaTextField.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Insira uma palavra no campo de resposta antes de enviar.");
        }

    }//GEN-LAST:event_enviarButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        MenuInicial mi = new MenuInicial();
        mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fase1().setVisible(true);
            }
        });
    }

    private void readTableFase1() {
        fase1Table.getColumnModel().getColumn(0).setPreferredWidth(40);
        fase1Table.getColumnModel().getColumn(1).setPreferredWidth(360);
        
        DefaultTableModel model = (DefaultTableModel) fase1Table.getModel();
        model.setNumRows(0);

        PalavraDAO dao = new PalavraDAO();

        for (Palavra p : dao.readPalavrasFase1()) {
            Object[] dados = {p.getId(), p.getDica()};
            model.addRow(dados);
        }
    }

    private int calcularPontuacao() {
        double d = 10.0 / numeroTentativas * 100;
        int i = (int) Math.round(d);
        return i;
    }

    private void preencherInterpretada() {
        interpretada1.setText("i");
        interpretada2_len3.setText("n");
        interpretada3.setText("t");
        interpretada4_colchete8.setText("e");
        interpretada5.setText("r");
        interpretada6.setText("p");
        interpretada7_return1.setText("r");
        interpretada8.setText("e");
        interpretada9.setText("t");
        interpretada10_variavel5.setText("a");
        interpretada11.setText("d");
        interpretada12.setText("a");
    }

    private void preencherInput() {
        import1.setText("i");
        input2.setText("n");
        input3.setText("p");
        return4_input4.setText("u");
        input5.setText("t");
    }

    private void preencherPrint() {
        import3_print1.setText("p");
        print2.setText("r");
        print3.setText("i");
        return6_print4.setText("n");
        print5.setText("t");
    }

    private void preencherTurtle() {
        hashtag5_turtle1.setText("t");
        turtle2.setText("u");
        turtle3.setText("r");
        import6_turtle4.setText("t");
        turtle5.setText("l");
        turtle6.setText("e");
    }

    private void preencherHashtag() {
        hashtag1.setText("h");
        hashtag2.setText("a");
        hashtag3.setText("s");
        hashtag4.setText("h");
        hashtag5_turtle1.setText("t");
        hashtag6.setText("a");
        hashtag7.setText("g");
    }

    private void preencherLen() {
        len1.setText("l");
        len2.setText("e");
        interpretada2_len3.setText("n");
    }

    private void preencherColchete() {
        colchete1.setText("c");
        colchete2.setText("o");
        colchete3.setText("l");
        colchete4.setText("c");
        colchete5.setText("h");
        colchete6.setText("e");
        colchete7.setText("t");
        interpretada4_colchete8.setText("e");
    }

    private void preencherImport() {
        import1.setText("i");
        import2.setText("m");
        import3_print1.setText("p");
        import4.setText("o");
        import5.setText("r");
        import6_turtle4.setText("t");
    }

    private void preencherReturn() {
        interpretada7_return1.setText("r");
        return2.setText("e");
        return3.setText("t");
        return4_input4.setText("u");
        return5.setText("r");
        return6_print4.setText("n");
    }

    private void preencherVariavel() {
        variavel1.setText("v");
        variavel2.setText("a");
        variavel3.setText("r");
        variavel4.setText("i");
        interpretada10_variavel5.setText("a");
        variavel6.setText("v");
        variavel7.setText("e");
        variavel8.setText("l");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField colchete1;
    private javax.swing.JTextField colchete2;
    private javax.swing.JTextField colchete3;
    private javax.swing.JTextField colchete4;
    private javax.swing.JTextField colchete5;
    private javax.swing.JTextField colchete6;
    private javax.swing.JTextField colchete7;
    private javax.swing.JButton enviarButton;
    private javax.swing.JTable fase1Table;
    private javax.swing.JTextField hashtag1;
    private javax.swing.JTextField hashtag2;
    private javax.swing.JTextField hashtag3;
    private javax.swing.JTextField hashtag4;
    private javax.swing.JTextField hashtag5_turtle1;
    private javax.swing.JTextField hashtag6;
    private javax.swing.JTextField hashtag7;
    private javax.swing.JTextField import1;
    private javax.swing.JTextField import2;
    private javax.swing.JTextField import3_print1;
    private javax.swing.JTextField import4;
    private javax.swing.JTextField import5;
    private javax.swing.JTextField import6_turtle4;
    private javax.swing.JTextField input2;
    private javax.swing.JTextField input3;
    private javax.swing.JTextField input5;
    private javax.swing.JTextField interpretada1;
    private javax.swing.JTextField interpretada10_variavel5;
    private javax.swing.JTextField interpretada11;
    private javax.swing.JTextField interpretada12;
    private javax.swing.JTextField interpretada2_len3;
    private javax.swing.JTextField interpretada3;
    private javax.swing.JTextField interpretada4_colchete8;
    private javax.swing.JTextField interpretada5;
    private javax.swing.JTextField interpretada6;
    private javax.swing.JTextField interpretada7_return1;
    private javax.swing.JTextField interpretada8;
    private javax.swing.JTextField interpretada9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField len1;
    private javax.swing.JTextField len2;
    private javax.swing.JTextField print2;
    private javax.swing.JTextField print3;
    private javax.swing.JTextField print5;
    private javax.swing.JTextField respostaTextField;
    private javax.swing.JTextField return2;
    private javax.swing.JTextField return3;
    private javax.swing.JTextField return4_input4;
    private javax.swing.JTextField return5;
    private javax.swing.JTextField return6_print4;
    private javax.swing.JButton sairButton;
    private javax.swing.JTextField turtle2;
    private javax.swing.JTextField turtle3;
    private javax.swing.JTextField turtle5;
    private javax.swing.JTextField turtle6;
    private javax.swing.JTextField variavel1;
    private javax.swing.JTextField variavel2;
    private javax.swing.JTextField variavel3;
    private javax.swing.JTextField variavel4;
    private javax.swing.JTextField variavel6;
    private javax.swing.JTextField variavel7;
    private javax.swing.JTextField variavel8;
    // End of variables declaration//GEN-END:variables
}
